# Generated by Django 3.1.5 on 2021-01-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210126_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addressNumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
